name: Hypster-Updater
version: '1.0-SNAPSHOT'
main: root.hypster.Hypster_Updater
api-version: 1.19
authors: [axellFumioo]
description: Automatic update for Player Server
website: https://axellfumioo.my.id
